name: notification_course
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  audio_service: ^0.18.10
  audio_video_progress_bar: ^1.0.1
  awesome_notifications: ^0.7.4+1
  awesome_notifications_fcm: ^0.7.4+1
  clear_all_notifications: ^0.0.3
  eraser: ^2.0.1
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_background_service: ^3.0.1
  fluttertoast: ^8.2.2
  get_it: ^7.6.0
  just_audio: ^0.9.34

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/profile_photo.png
